version: '3.8'

services:
  laravel:
    build:
      context: ./myChampionship-backend
    container_name: laravel
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./myChampionship-backend:/var/www
      - ./myChampionship-backend/vendor:/var/www/vendor
    networks:
      - app-network
    ports:
      - "8000:9000"

  angular:
    build:
      context: ./myChampionship-frontend
    container_name: angular
    restart: unless-stopped
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    volumes:
      - ./myChampionship-frontend:/app
    networks:
      - app-network
    ports:
      - "4200:4200"

networks:
  app-network:
    driver: bridge
